# Generated by Django 5.2.17 on 2026-09-18 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome collezione"),
                ),
                ("citta", models.CharField(blank=True, max_length=255)),
                ("paese", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Collezione",
                "verbose_name_plural": "Collezioni — solo sito",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="FonteBibliografica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_fonte", models.CharField(blank=True, max_length=100)),
                ("autore", models.TextField(blank=True)),
                ("curatore", models.TextField(blank=True)),
                ("contributi", models.TextField(blank=True)),
                ("titolo", models.TextField()),
                ("titolo_variante", models.TextField(blank=True)),
                ("titolo_periodico", models.CharField(blank=True, max_length=255)),
                ("numero_periodico", models.CharField(blank=True, max_length=100)),
                ("volume", models.CharField(blank=True, max_length=100)),
                ("editore", models.CharField(blank=True, max_length=255)),
                ("luogo", models.CharField(blank=True, max_length=255)),
                ("anno", models.IntegerField(blank=True, null=True)),
                ("data_pubblicazione", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Fonte bibliografica",
                "verbose_name_plural": "Fonti bibliografiche",
                "ordering": ["autore", "anno"],
            },
        ),
        migrations.CreateModel(
            name="Mostra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titolo",
                    models.CharField(max_length=500, verbose_name="Titolo mostra"),
                ),
                ("curatore", models.CharField(blank=True, max_length=500)),
                (
                    "data_inizio",
                    models.DateField(
                        blank=True,
                        help_text="Spesso non ancora compilata: vedi anno_testo.",
                        null=True,
                    ),
                ),
                ("data_fine", models.DateField(blank=True, null=True)),
                (
                    "periodo_testo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Periodo (testo)"
                    ),
                ),
                (
                    "anno_testo",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Anno (testo)"
                    ),
                ),
                ("da_verificare", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Mostra",
                "verbose_name_plural": "Mostre",
                "ordering": ["anno_testo", "titolo"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome sede")),
                ("istituzione", models.CharField(blank=True, max_length=255)),
                ("citta", models.CharField(blank=True, max_length=255)),
                ("indirizzo", models.CharField(blank=True, max_length=255)),
                ("provincia", models.CharField(blank=True, max_length=255)),
                ("regione", models.CharField(blank=True, max_length=255)),
                ("paese", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedi",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TipoCollezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo collezione",
                "verbose_name_plural": "Tipi collezione — solo sito",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoEsposizione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tipo esposizione"
                    ),
                ),
                (
                    "normalizzato",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Tipo esposizione (normalizzato)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo esposizione",
                "verbose_name_plural": "Tipi esposizione",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TipoFonteBibliografica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo fonte bibliografica",
                "verbose_name_plural": "Tipi fonte bibliografica",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoImmagine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("descrizione_tipo", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Tipo immagine",
                "verbose_name_plural": "Tipi immagine",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoOpera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Tipo opera",
                "verbose_name_plural": "Tipi opera (sezioni del catalogo) — solo sito",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoRiferimentoInFonte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo riferimento in fonte",
                "verbose_name_plural": "Tipi riferimento in fonte",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MostraSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inizio_sede",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Data inizio (testo)"
                    ),
                ),
                (
                    "data_fine_sede",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Data fine (testo)"
                    ),
                ),
                ("ordine", models.PositiveIntegerField(default=0)),
                (
                    "mostra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.mostra",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogo.sede"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede della mostra",
                "verbose_name_plural": "Sedi della mostra",
                "ordering": ["ordine"],
                "unique_together": {("mostra", "sede")},
            },
        ),
        migrations.CreateModel(
            name="Opera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_scheda", models.CharField(blank=True, max_length=100)),
                (
                    "numero_archivio",
                    models.CharField(
                        help_text="Identificativo permanente dell'opera, usato anche nell'URL pubblico.",
                        max_length=100,
                        unique=True,
                        verbose_name="Numero di archivio",
                    ),
                ),
                ("titolo", models.TextField()),
                (
                    "anno_testo",
                    models.CharField(
                        blank=True,
                        help_text='Es. "1965 ca."',
                        max_length=50,
                        verbose_name="Anno (testo)",
                    ),
                ),
                (
                    "anno_inizio",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Campo solo sito (Access ha solo 'Anno' come testo libero) — usato per il filtro per anno.",
                        null=True,
                    ),
                ),
                ("anno_fine", models.PositiveIntegerField(blank=True, null=True)),
                ("tecnica", models.TextField(blank=True)),
                ("supporto", models.CharField(blank=True, max_length=255)),
                ("altezza", models.FloatField(blank=True, null=True)),
                ("larghezza", models.FloatField(blank=True, null=True)),
                ("profondita", models.FloatField(blank=True, null=True)),
                ("diametro", models.FloatField(blank=True, null=True)),
                ("unita_misura", models.CharField(blank=True, max_length=20)),
                ("dimensioni_note", models.TextField(blank=True)),
                ("firma", models.TextField(blank=True)),
                ("iscrizioni", models.TextField(blank=True)),
                ("stato_conservazione", models.CharField(blank=True, max_length=255)),
                ("collocazione", models.TextField(blank=True)),
                ("provenienza", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "pubblicata",
                    models.BooleanField(
                        default=False,
                        help_text="Solo le opere pubblicate compaiono sul sito pubblico.",
                    ),
                ),
                (
                    "collezione",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campo solo sito — Access ha solo il testo libero 'collocazione'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opere",
                        to="catalogo.collezione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opera",
                "verbose_name_plural": "Opere",
                "ordering": ["anno_testo", "numero_archivio"],
            },
        ),
        migrations.CreateModel(
            name="OperaMostra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collocazione_in_fonte", models.TextField(blank=True)),
                ("numero_catalogo", models.CharField(blank=True, max_length=100)),
                ("titolo_alternativo", models.TextField(blank=True)),
                ("da_verificare", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("eliminata", models.BooleanField(default=False)),
                ("data_eliminazione", models.DateTimeField(blank=True, null=True)),
                ("motivo_eliminazione", models.TextField(blank=True)),
                (
                    "mostra_sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.mostrasede",
                        verbose_name="Sede della mostra",
                    ),
                ),
                (
                    "opera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalogo.opera"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opera in mostra",
                "verbose_name_plural": "Opere in mostra",
                "ordering": ["mostra_sede"],
                "unique_together": {("opera", "mostra_sede")},
            },
        ),
        migrations.AddField(
            model_name="opera",
            name="mostre_sedi",
            field=models.ManyToManyField(
                related_name="opere",
                through="catalogo.OperaMostra",
                to="catalogo.mostrasede",
            ),
        ),
        migrations.CreateModel(
            name="RiferimentoBibliografico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_opera_citata",
                    models.CharField(
                        blank=True,
                        help_text="Se la fonte cita l'opera con un titolo diverso da quello corrente.",
                        max_length=500,
                    ),
                ),
                ("pagina", models.CharField(blank=True, max_length=100)),
                ("tavola", models.CharField(blank=True, max_length=100)),
                ("numero_riproduzione", models.CharField(blank=True, max_length=100)),
                ("sala", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("da_verificare", models.BooleanField(default=False)),
                ("eliminata", models.BooleanField(default=False)),
                ("data_eliminazione", models.DateTimeField(blank=True, null=True)),
                ("motivo_eliminazione", models.TextField(blank=True)),
                (
                    "fonte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citazioni",
                        to="catalogo.fontebibliografica",
                    ),
                ),
                (
                    "opera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bibliografia",
                        to="catalogo.opera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riferimento bibliografico",
                "verbose_name_plural": "Riferimenti bibliografici",
                "ordering": ["fonte"],
                "unique_together": {("opera", "fonte")},
            },
        ),
        migrations.AddField(
            model_name="opera",
            name="fonti",
            field=models.ManyToManyField(
                related_name="opere",
                through="catalogo.RiferimentoBibliografico",
                to="catalogo.fontebibliografica",
            ),
        ),
        migrations.AddField(
            model_name="mostra",
            name="sedi",
            field=models.ManyToManyField(
                related_name="mostre", through="catalogo.MostraSede", to="catalogo.sede"
            ),
        ),
        migrations.AddField(
            model_name="collezione",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.tipocollezione",
            ),
        ),
        migrations.AddField(
            model_name="mostra",
            name="tipo_esposizione",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.tipoesposizione",
            ),
        ),
        migrations.AddField(
            model_name="fontebibliografica",
            name="tipo_pubblicazione",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.tipofontebibliografica",
            ),
        ),
        migrations.CreateModel(
            name="Immagine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="opere/%Y/")),
                (
                    "nome_file",
                    models.CharField(
                        blank=True,
                        help_text="Nome file originale (riferimento di importazione).",
                        max_length=255,
                    ),
                ),
                (
                    "percorso_relativo",
                    models.CharField(
                        blank=True,
                        help_text="Percorso originale in Access (riferimento di importazione).",
                        max_length=255,
                    ),
                ),
                ("segni_particolari", models.TextField(blank=True)),
                ("stato_verifica", models.CharField(blank=True, max_length=100)),
                ("descrizione", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                ("ordine_visualizzazione", models.PositiveIntegerField(default=0)),
                ("eliminata", models.BooleanField(default=False)),
                ("data_eliminazione", models.DateTimeField(blank=True, null=True)),
                ("eliminata_da", models.CharField(blank=True, max_length=255)),
                ("motivo_eliminazione", models.TextField(blank=True)),
                (
                    "opera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immagini",
                        to="catalogo.opera",
                    ),
                ),
                (
                    "tipo_immagine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.tipoimmagine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Immagine",
                "verbose_name_plural": "Immagini",
                "ordering": ["ordine_visualizzazione", "id"],
            },
        ),
        migrations.AddField(
            model_name="opera",
            name="tipo_opera",
            field=models.ForeignKey(
                help_text="Sezione del catalogo — campo solo sito, non presente in Access.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opere",
                to="catalogo.tipoopera",
            ),
        ),
    ]
