# Generated by Django 5.2.17 on 2026-08-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome collezione"),
                ),
                ("citta", models.CharField(blank=True, max_length=255)),
                ("paese", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Collezione",
                "verbose_name_plural": "Collezioni",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="FonteBibliografica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_fonte", models.CharField(blank=True, max_length=100)),
                ("tipo_pubblicazione", models.CharField(blank=True, max_length=100)),
                ("autore", models.TextField(blank=True)),
                ("curatore", models.TextField(blank=True)),
                ("contributi", models.TextField(blank=True)),
                ("titolo", models.TextField()),
                ("titolo_periodico", models.CharField(blank=True, max_length=255)),
                ("editore", models.CharField(blank=True, max_length=255)),
                ("luogo", models.CharField(blank=True, max_length=255)),
                ("anno", models.CharField(blank=True, max_length=20)),
                ("volume", models.CharField(blank=True, max_length=100)),
                ("numero_periodico", models.CharField(blank=True, max_length=100)),
                ("isbn", models.CharField(blank=True, max_length=50)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Fonte bibliografica",
                "verbose_name_plural": "Fonti bibliografiche",
                "ordering": ["autore", "anno"],
            },
        ),
        migrations.CreateModel(
            name="Mostra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titolo",
                    models.CharField(max_length=500, verbose_name="Titolo mostra"),
                ),
                ("anno_inizio", models.PositiveIntegerField(blank=True, null=True)),
                ("anno_fine", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "data_testo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Date (testo)"
                    ),
                ),
                ("curatore", models.CharField(blank=True, max_length=500)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Mostra",
                "verbose_name_plural": "Mostre",
                "ordering": ["-anno_inizio", "titolo"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome sede")),
                ("citta", models.CharField(blank=True, max_length=255)),
                ("provincia", models.CharField(blank=True, max_length=255)),
                ("regione", models.CharField(blank=True, max_length=255)),
                ("paese", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedi",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TipoCollezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo collezione",
                "verbose_name_plural": "Tipi collezione",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoImmagine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo immagine",
                "verbose_name_plural": "Tipi immagine",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoMostra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo mostra",
                "verbose_name_plural": "Tipi mostra",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoOpera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Tipo opera",
                "verbose_name_plural": "Tipi opera (sezioni del catalogo)",
                "ordering": ["ordine", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bibliografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("riferimento_pagine", models.CharField(blank=True, max_length=255)),
                ("riferimento_tavola", models.CharField(blank=True, max_length=255)),
                ("riferimento_numero", models.CharField(blank=True, max_length=255)),
                ("riprodotto", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                (
                    "fonte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citazioni",
                        to="catalogo.fontebibliografica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riferimento bibliografico",
                "verbose_name_plural": "Bibliografia",
                "ordering": ["fonte"],
            },
        ),
        migrations.CreateModel(
            name="Opera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_archivio",
                    models.CharField(
                        help_text="Identificativo permanente dell'opera (es. FDC-0001), usato anche nell'URL pubblico.",
                        max_length=100,
                        unique=True,
                        verbose_name="Numero di archivio",
                    ),
                ),
                ("titolo", models.TextField()),
                (
                    "anno_testo",
                    models.CharField(
                        blank=True,
                        help_text='Es. "1965 ca."',
                        max_length=50,
                        verbose_name="Anno (testo)",
                    ),
                ),
                (
                    "anno_inizio",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("anno_fine", models.PositiveIntegerField(blank=True, null=True)),
                ("tecnica", models.TextField(blank=True)),
                (
                    "dimensioni_testo",
                    models.CharField(
                        blank=True, help_text='Es. "cm 67 x 49"', max_length=255
                    ),
                ),
                ("altezza_cm", models.FloatField(blank=True, null=True)),
                ("larghezza_cm", models.FloatField(blank=True, null=True)),
                ("profondita_cm", models.FloatField(blank=True, null=True)),
                ("diametro_cm", models.FloatField(blank=True, null=True)),
                ("provenienza", models.TextField(blank=True)),
                (
                    "segni_recto",
                    models.TextField(
                        blank=True, verbose_name="Segni e iscrizioni (recto)"
                    ),
                ),
                (
                    "segni_verso",
                    models.TextField(
                        blank=True, verbose_name="Segni e iscrizioni (verso)"
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "pubblicata",
                    models.BooleanField(
                        default=False,
                        help_text="Solo le opere pubblicate compaiono sul sito pubblico.",
                    ),
                ),
                (
                    "collezione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opere",
                        to="catalogo.collezione",
                    ),
                ),
                (
                    "fonti",
                    models.ManyToManyField(
                        related_name="opere",
                        through="catalogo.Bibliografia",
                        to="catalogo.fontebibliografica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opera",
                "verbose_name_plural": "Opere",
                "ordering": ["anno_inizio", "numero_archivio"],
            },
        ),
        migrations.AddField(
            model_name="bibliografia",
            name="opera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bibliografia",
                to="catalogo.opera",
            ),
        ),
        migrations.CreateModel(
            name="OperaMostra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sala", models.CharField(blank=True, max_length=100)),
                ("numero_catalogo", models.CharField(blank=True, max_length=100)),
                ("nota", models.TextField(blank=True)),
                (
                    "mostra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.mostra",
                    ),
                ),
                (
                    "opera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalogo.opera"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opera in mostra",
                "verbose_name_plural": "Opere in mostra",
                "ordering": ["mostra"],
                "unique_together": {("opera", "mostra")},
            },
        ),
        migrations.AddField(
            model_name="opera",
            name="mostre",
            field=models.ManyToManyField(
                related_name="opere",
                through="catalogo.OperaMostra",
                to="catalogo.mostra",
            ),
        ),
        migrations.CreateModel(
            name="MostraSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("ruolo_sede", models.CharField(blank=True, max_length=100)),
                ("sala_sezione", models.CharField(blank=True, max_length=255)),
                ("nota", models.TextField(blank=True)),
                (
                    "mostra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.mostra",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogo.sede"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede della mostra",
                "verbose_name_plural": "Sedi della mostra",
                "ordering": ["ordine"],
                "unique_together": {("mostra", "sede")},
            },
        ),
        migrations.AddField(
            model_name="mostra",
            name="sedi",
            field=models.ManyToManyField(
                related_name="mostre", through="catalogo.MostraSede", to="catalogo.sede"
            ),
        ),
        migrations.AddField(
            model_name="collezione",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.tipocollezione",
            ),
        ),
        migrations.CreateModel(
            name="Immagine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="opere/%Y/")),
                ("didascalia", models.CharField(blank=True, max_length=500)),
                ("descrizione", models.TextField(blank=True)),
                ("ordine_visualizzazione", models.PositiveIntegerField(default=0)),
                (
                    "opera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immagini",
                        to="catalogo.opera",
                    ),
                ),
                (
                    "tipo_immagine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.tipoimmagine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Immagine",
                "verbose_name_plural": "Immagini",
                "ordering": ["ordine_visualizzazione", "id"],
            },
        ),
        migrations.AddField(
            model_name="mostra",
            name="tipo_mostra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.tipomostra",
            ),
        ),
        migrations.AddField(
            model_name="opera",
            name="tipo_opera",
            field=models.ForeignKey(
                help_text="Sezione del catalogo (dipinti/sculture, opere su carta, edizioni...).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opere",
                to="catalogo.tipoopera",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bibliografia",
            unique_together={("opera", "fonte")},
        ),
    ]
